# Application configuration for bomdia

[model]
dia_checkpoint = "nari-labs/Dia-1.6B-0626"
dia_checkpoint_revision = "main"
# Optional: Specify the compute precision "float16", "float32", "bfloat16"
# Defaults will use automatic detection.
dia_compute_dtype = "float32"
# Optional: Specify the compute device. Options: "auto", "cuda", "mps", "cpu".
# Defaults to "auto" for automatic detection.
# device = "cpu"

# LiteLLM model string (e.g., "openai/gpt-4o-mini", "ollama/llama3", "claude-3-haiku-20240307")
llm_spec = "openai/gpt-4o-mini"

[model.dia_generate_params]
# Uncomment and set any of the following parameters to override the DiaTTS
# model's internal defaults. Only the parameters you provide will be used.
# cfg_scale = 3.0
cfg_scale = 4.0
# temperature = 1.2
# top_p = 0.95
# top_k = 45
# max_tokens for audio generation default is 3072
max_tokens = 1096
# use_torch_compile = false

[model.parameters]
temperature = 0.5
max_tokens = 4096

[pipeline]
context_window = 2
pause_placeholder = "[insert-verbal-tag-for-pause]"
max_tag_rate = 0.15
avg_wps = 2.5
max_new_tokens_cap = 1600
# Optionally define a seed for specific voice pair and genation characteristics
# seed = 12345

[tags]
verbal_tags = [
    "(laughs)",
    "(clears throat)",
    "(sighs)",
    "(gasps)",
    "(coughs)",
    "(singing)",
    "(sings)",
    "(mumbles)",
    "(beep)",
    "(groans)",
    "(sniffs)",
    "(claps)",
    "(screams)",
    "(inhales)",
    "(exhales)",
    "(applause)",
    "(burps)",
    "(humming)",
    "(sneezes)",
    "(chuckle)",
    "(whistles)",
]

line_combiners = [
    "…um,",
    "- uh -",
    "— hmm —",
]

[director_agent.rate_control]
# The target ratio of lines that should receive a new verbal tag (e.g., 0.10 for 10%).
target_tag_rate = 0.16
# The maximum number of "burst" tags the agent can inject above its target rate.
# This allows it to handle emotionally dense scenes.
tag_burst_allowance = 3

[director_agent.review]
# Mode for the Director's final review.
# "procedural": Fast, rule-based tag pruning (default).
# "llm": Slower, higher-quality LLM-based curation.
mode = "llm"

[persistence]
rehearsal_checkpoint_path = "rehearsal_checkpoints.sqlite"

[audio]
output_format = "mp3"
sampling_rate = 44100
sample_width = 2
channels = 1
