[director_agent]
# Prompt for the Director's initial, one-time analysis of the entire script.
global_summary_prompt = """
You are a script analyst. Read the entire following transcript and provide a concise summary covering three key areas. This summary will be used to guide another AI in performing the dialogue, so clarity and insight are crucial.

1.  **Overall Topic:** What is the main subject of the conversation?
2.  **Speaker Relationship:** Describe the dynamic between the speakers (e.g., friendly colleagues, confrontational rivals, interviewer and subject).
3.  **Emotional Arc:** Describe the flow of emotion from the beginning to the end of the conversation (e.g., "Starts with lighthearted banter, moves to a serious disagreement, and ends with a reluctant compromise.").

Here is the transcript:
---
{transcript_text}
---
"""

# Prompt to define narrative moments.
moment_definition_prompt = """
You are a script director, preparing your notes for the next performance.
{previous_moment_segment}

Your Task:
Analyze the upcoming script to define the **next `current moment`**. A `current moment` is a continuous, self-contained beat with a consistent emotional tone and narrative purpose. It starts at the first unassigned line and ends when the topic, intention, or emotional tone clearly shifts.

Upcoming Script (with global line numbers):
---
{forward_script_slice_text}
---

Your Direction:
Based on the script, identify the boundaries of the very next moment. Respond with a single JSON object that provides your complete direction.

{{
  "moment_summary": "Concise description of what is happening in this new moment. What is the core emotion and the characters' primary intentions?",
  "directors_notes": "Actionable notes for the actors. What should they be feeling or trying to achieve during this moment?",
  "start_line": {line_number},
  "end_line": <The line number where this moment naturally concludes>
}}

Respond with ONLY the JSON object, no other text.
"""

previous_moment_template = """
The Previous Moment:
You just completed a moment described as: "{last_moment_summary}".
It concluded on line {last_moment_end_line} with the finalized performance: "{last_finalized_line_text}".
"""

quota_exceeded_note = """
(Automated message: The production's budget for verbal tags has been met. Do not add any new parenthetical tags.)
"""


[actor_agent]
# Template for the Actor's moment-based task.
moment_task_directive_template = """
You are a voice actor performing lines from a script. Your performance should be natural and enhance the written dialogue.

**Context:**
- **Global Summary:** {global_summary}

**Your Task:**
Perform the following lines as a cohesive moment:
{moment_text}

**Available Verbalizations:**
- **For emotional expression:** You may add tags from the following list: {available_verbal_tags}
- **For pauses/hesitations:** When replacing `[insert-verbal-tag-for-pause]`, you must use one of the emotional expressions, or one following: {available_line_combiners}


**Performance Rules:**
1.  **Regarding `[insert-verbal-tag-for-pause]`:** This placeholder marks a technical break in a single continuous thought. Your job is to bridge this gap naturally by replacing it with an appropriate option from the list above. If no verbalization feels right, you MUST replace it with a single space to connect the parts.
2.  **Regarding New Verbal Tags:**
    *   You have a budget to add up to **{token_budget:.0f}** new verbal tags for emotional expression across **all the lines** in this moment.
    *   You may add at most **one** new tag to any single line, and only at the beginning of the line.
    *   Only use your budget on tags that are strongly motivated by the emotional context. If no new tags feel natural, it is better to add zero.
{constraints_text}

**Output Format:**
Respond with a JSON object that maps each line's local index within the moment to its performed text:
{{
  "line_0": "Performed text for the first line in the moment",
  "line_1": "Performed text for the second line in the moment"
}}

Make sure to return ONLY the JSON object, with no additional text or markdown formatting.
"""
